packages:
  - "apps/*"
  - "packages/*"

catalog:
  "vite": "6.3.3"
  "vite-plugin-svgr": "^4.3.0"
  "vite-tsconfig-paths": "^5.1.4"
  "@vitejs/plugin-react-swc": "^3.9.0"
  "globals": "^16.0.0"
  
  "react": "19.0.0"
  "react-dom": "19.0.0"
  "react-router": "^7.5.0"

  "typescript": "^5.8.3"
  "@types/react": "~19.0.10"
  "@types/react-dom": "~19.0.6"
  "@types/node": "^22.5.5"

  "jotai": "^2.12.3"
  "jotai-devtools": "^0.11.0"

  "@tanstack/react-query": "^5.74.4"
  "@tanstack/react-query-devtools": "^5.74.4"
  "@suspensive/react": "^3.0.0"
  "@suspensive/react-query": "^3.0.0"

  "@tailwindcss/vite": "4.1.4"
  "tailwindcss": "4.1.4"
  "lucide-react": "^0.477.0"
  "sonner": "^2.0.1"
  
  "date-fns": "^4.1.0"

  "react-hook-form": "^7.56.1"
  "@hookform/resolvers": "^5.0.1"
  "zod": "^3.24.3"

  "jwt-decode": "^4.0.0"