/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_loginAsParticipant'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_refreshToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorDto: {
      readonly code: string;
      readonly message: string;
    };
    PaginationDto: {
      readonly count: number;
      readonly hasNext: boolean;
      readonly hasPrev: boolean;
      readonly page: number;
      readonly pageSize: number;
      readonly totalCount: number;
      readonly totalPage: number;
    };
    LoginReqDto: {
      email: string;
      password: string;
    };
    RefreshTokenReqDto: {
      authId: string;
      refreshToken: string;
    };
    TokenResDto: {
      accessToken: string;
      refreshToken: string;
      /** Format: date-time */
      refreshTokenExpiresAt: string;
    };
    TokenResDtoResponseDto: {
      error?: components['schemas']['ErrorDto'];
      payload?: components['schemas']['TokenResDto'];
      readonly success: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_loginAsParticipant: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginReqDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenResDtoResponseDto'];
        };
      };
    };
  };
  AuthController_refreshToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenReqDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenResDtoResponseDto'];
        };
      };
    };
  };
}
